server:
  port: 9100
eureka:
  instance:
    hostname: localhost
    port: 7000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
spring:
  profiles:
    active: dev
  application:
    name: employee-login-service
