server:
  port: 9100
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka
spring:
  profiles:
    active: dev
  application:
    name: employee-login-service
