server:
  port: 9200
spring:
  profiles:
    active: dev
  application:
    name: employee-management-service
eureka:
  instance:
    hostname: localhost
    port: 7000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

service:
  url:
    login: employee-login-service
