
node {
    stage('Checkout') {
        checkout scm
    }
    stage('Preparation') {
            dir('employee-eureka-server') {
                sh 'ls'
            pom = readMavenPom file: 'pom.xml'
            sh 'echo pom.version'
            IMAGE = pom.artifactId
            VERSION = pom.version
            sh 'chmod +x mvnw'
            }
    }
    stage ('Compile Stage') {
        dir('employee-eureka-server') {
            
            sh'./mvnw clean compile'
        }
    }
}
