
pipeline =  {
    stage('Checkout') {
        checkout scm
    }
    stage('Preparation') {
        dir('employee-eureka-server') {
            pom = readMavenPom file: 'pom.xml'
            sh 'echo pom.version'
            IMAGE = pom.artifactId
            VERSION = pom.version
            sh 'chmod +x mvnw'
        }
    }
    stage ('Compile Stage') {
        dir('employee-eureka-server') {
            sh'./mvnw clean compile'
        }
    } 
    stage ('Testing Stage') {
        dir('employee-eureka-server') {
            sh'./mvnw test'
        }
    }
    stage ('Package Stage') {
        dir('employee-eureka-server') {
            sh'./mvnw clean package'
        }
    }
    stage('Sonar Scanner') {
        dir ('employee-eureka-server') {
            SONAR = credentials('sonar')
            sh './mvnw sonar:sonar -Dsonar.login=${sonarLogin} -Dsonar.host.url=http://sonarqube:9000'
            // def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
            // withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
            // sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=employee-eureka-server -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=src/main/ -Dsonar.tests=src/test/ -Dsonar.language=java -Dsonar.java.binaries=."
            // }
        }
    }
    stage ('Build/Publish') {
        dir ('employee-eureka-server') {
            docker.withRegistry('https://index.docker.io/v1/', 'docker') {
            docker.build("gagandeep39/employee-eureka-server:${VERSION}", '.').push()
            docker.build("gagandeep39/employee-eureka-server:latest", '.').push()
            }
        }
    }
    stage ('Deploy on this Server') {
        dir ('employee-eureka-server') {
            sh 'echo ${VERSION}'
            sh 'docker stop employee-eureka-server || echo Container is not on'
            sh 'docker container rm -f employee-eureka-server || echo Container doesnt exists'
            docker.image('gagandeep39/employee-eureka-server:' + VERSION).run('-p 7000:7000 --name employee-eureka-server -m=800m -h employee-eureka-server')
            sh 'docker image prune -f'
        }
    }
}
postFailure = {
    def to = emailextrecipients([
        [$class: 'CulpritsRecipientProvider'],
        [$class: 'DevelopersRecipientProvider'],
        [$class: 'RequesterRecipientProvider']
    ])

    currentBuild.result = 'FAILURE'
    // set variables
    def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}"
    def content = '${JELLY_SCRIPT,template="html"}'
    // send email
    if (to != null && !to.isEmpty()) {
        emailext(body: content, mimeType: 'text/html',
                replyTo: '$DEFAULT_REPLYTO', subject: subject,
                to: to, attachLog: true )
    }
}

node {
    try {
        pipeline()
    }
    catch (e) {
        postFailure()
    }
}